image: docker:latest

services:
  - docker:dind

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/awg/jobs-parser .
    - docker push registry.gitlab.com/awg/jobs-parser
  only:
    - tags
